services:
  web:
    image: nexusrepo1.eastus.cloudapp.azure.com:8083/dockercomposetest:##TAGS##
    ports:
      - 32921:5000
    volumes:
      - /home/azureuser/containerdatafiles:/code/omerco
  redis:
    image: redis:alpine
